export 'about/about_page.dart';
export 'announce/announce_page.dart';
export 'chart/chart_page.dart';
export 'common/year_page.dart';
export 'group/group_page.dart';
export 'nearby/nearby_page.dart';
export 'notify/notify_page.dart';
export 'stepcount/stepcount_page.dart';
export 'stepcount/record_page.dart';